// Midori booking catalog: single source of truth for services, packages, add-ons and prices.
// Source: "Midori Package Guide" (Service and Package Guide, prepared October 1, 2026).
// The internal appendix (market comparison, costs) is intentionally NOT included here.
//
// This file is plain data with no imports, so the exact same file is used by the
// backend (authoritative pricing) and the website (live totals). If you change a
// price here, copy this file to the frontend (src/booking/catalog.js) as well. The
// server always recalculates totals, so an out-of-date browser copy can never
// change what a client is quoted.

export const CATALOG_VERSION = "2026-10-01";
export const CURRENCY = "USD";

export const BUSINESS = {
  name: "Midori Media Company LLC",
  brand: "MidoriClicks",
  location: "Overland Park, Kansas",
  serviceArea: "Kansas and Missouri",
  travelNote: "Travel fees may apply outside the Kansas City area. We confirm any travel fee with you before you book.",
  droneNote: "Drone flights depend on FAA rules, the venue, airspace and the weather.",
  livestreamNote: "Live streaming needs reliable internet from you or the venue, and a stream cannot be redone if it fails.",
  allPackagesInclude: {
    wedding: ["Online gallery", "Print release", "Timeline planning call"],
    small_event: [
      "Online gallery",
      "Print release",
      "Portable lighting for indoor rooms",
      "Two camera bodies per shooter",
      "Short planning call",
      "Editing, color work and cloud backup",
    ],
  },
};

export const CATEGORIES = [
  {
    id: "wedding",
    label: "Weddings",
    tagline: "Photo and film for your wedding day",
    description: "Five packages, from a 4-hour celebration to a 16-hour luxury wedding. Every package includes photos and a film.",
    fromPrice: 2500,
  },
  {
    id: "multi_event_wedding",
    label: "Indian & multi-event weddings",
    tagline: "Sangeet, mehndi, wedding and more",
    description: "Weddings that run across two or three days with several events, built from our wedding packages.",
    fromPrice: 6900,
  },
  {
    id: "small_event",
    label: "Portraits & small events",
    tagline: "Birthdays, proposals, graduations, corporate",
    description: "Packages built around 1, 2 or 4 hours for birthdays, proposals, engagement parties, showers, graduations, anniversaries and company events.",
    fromPrice: 300,
  },
];

// ---------------------------------------------------------------------------
// Packages
// ---------------------------------------------------------------------------
export const PACKAGES = [
  // ----- Weddings (Part 1) -----
  {
    id: "essential",
    categories: ["wedding"],
    name: "Essential",
    price: 2500,
    hours: 4,
    team: "2 people",
    people: 2,
    drone: false,
    lights: "No",
    photos: "300+",
    retouched: 0,
    film: "3-5 min highlight film",
    extraHourRate: 250,
    bestFor: "Courthouse, micro wedding, backyard wedding, or a couple on a tighter budget.",
    receive: [
      "300+ edited photos in an online gallery with print release",
      "3-5 minute highlight film",
      "60-second vertical teaser for Instagram",
      "Ceremony audio, cleaned up and synced to the film",
      "5 sneak-peek photos within 72 hours",
    ],
    bring: [
      "Lead photographer and lead videographer, on site the full 4 hours",
      "Two camera bodies per shooter, so nothing is lost if one fails",
      "Wireless microphone and backup recorder for ceremony audio",
      "Gimbal and tripod for steady video",
      "Timeline planning call before the day",
      "Editing, color work and cloud backup",
    ],
    notIncluded: ["Drone", "Lights", "Engagement session (+$450)", "Album"],
    delivery: { sneakPeek: "5 photos in 72 hours", gallery: "4 weeks", film: "8 weeks" },
  },
  {
    id: "classic",
    categories: ["wedding"],
    name: "Classic",
    price: 3800,
    hours: 8,
    team: "2 people + drone",
    people: 2,
    drone: true,
    lights: "No",
    photos: "600+",
    retouched: 5,
    film: "5-8 min highlight film",
    extraHourRate: 250,
    bestFor: "A mainstream wedding at one venue, from ceremony through the first dances.",
    receive: [
      "600+ edited photos, 5 with high-end retouching",
      "5-8 minute highlight film",
      "Full ceremony film, start to finish",
      "60-second vertical teaser",
      "Aerial photos and clips, worked into the film",
      "45-minute engagement session",
      "10 sneak-peek photos within 72 hours",
    ],
    bring: [
      "Lead photographer and lead videographer for 8 hours",
      "Two camera bodies per shooter, gimbal, wireless microphones for the ceremony",
      "Drone, if FAA rules, venue and weather allow",
      "Planning call and a shot list built with the couple",
      "Editing, color work and cloud backup",
    ],
    notIncluded: ["Lights", "Separate toasts film", "Album", "Third shooter"],
    delivery: { sneakPeek: "10 photos in 72 hours", gallery: "4 weeks", film: "8 weeks" },
  },
  {
    id: "signature",
    categories: ["wedding"],
    name: "Signature",
    price: 5000,
    hours: 10,
    team: "3 people + drone",
    people: 3,
    drone: true,
    lights: "Basic kit",
    photos: "800+",
    retouched: 10,
    film: "6-10 min highlight film",
    extraHourRate: 350,
    bestFor: "A full-day wedding that wants getting ready, ceremony, toasts and reception covered by a real team.",
    receive: [
      "800+ edited photos, 10 with high-end retouching",
      "6-10 minute highlight film",
      "Ceremony film and a separate toasts film",
      "60-second teaser plus 1 social reel",
      "Aerial photos and clips",
      "1-hour engagement session",
      "10 sneak-peek photos within 72 hours",
    ],
    bring: [
      "Lead photographer, lead cinematographer and a second shooter",
      "Three people on site for 10 hours, so two moments are covered at once",
      "Two camera bodies per shooter, gimbal, wireless microphones, backup audio recorder",
      "Drone, if FAA rules, venue and weather allow",
      "Basic light kit for the reception",
      "Planning call, shot list and a venue check",
      "Editing, color work and cloud backup",
    ],
    notIncluded: ["Full lighting setup", "Album", "Raw video"],
    delivery: { sneakPeek: "10 photos in 72 hours", gallery: "4 weeks", film: "10 weeks" },
  },
  {
    id: "premier",
    categories: ["wedding", "multi_event_wedding"],
    name: "Premier",
    multiEventLabel: "Wedding day only",
    price: 6900,
    hours: 14,
    team: "3 people + drone + lights",
    people: 3,
    drone: true,
    lights: "Full kit",
    photos: "1,000+",
    retouched: "20-25",
    film: "8-15 min cinematic highlight film",
    extraHourRate: 350,
    bestFor: "Couples who want everything, from getting ready to the send-off.",
    receive: [
      "1,000+ edited photos, 20-25 with high-end retouching",
      "8-15 minute cinematic highlight film",
      "Ceremony film and a separate toasts film",
      "60-second teaser plus 3 social reels",
      "1-hour engagement session",
      "$500 credit toward a wedding album",
      "10 sneak-peek photos within 24 hours",
    ],
    bring: [
      "Lead photographer, lead cinematographer and a second shooter for 14 hours",
      "Full lighting kit for the reception, dance floor and dark venues",
      "Two camera bodies per shooter, gimbal, wireless microphones, backup audio recorder",
      "Drone, if FAA rules, venue and weather allow",
      "Planning call, shot list, venue check and a timeline built with the couple",
      "Album design help",
      "Editing, color work and cloud backup",
    ],
    notIncluded: ["Raw video clips (+$550)"],
    delivery: { sneakPeek: "10 photos in 24 hours", gallery: "6 weeks", film: "10 weeks" },
  },
  {
    id: "legacy",
    categories: ["wedding", "multi_event_wedding"],
    name: "Legacy",
    multiEventLabel: "Wedding day plus one event, in one booking",
    price: 10500,
    hours: 16,
    hoursLabel: "16 hours, or two events",
    team: "4 people + drone + lights",
    people: 4,
    drone: true,
    lights: "Full kit",
    photos: "1,500+",
    retouched: 40,
    film: "10-20 min documentary-style film",
    extraHourRate: 450,
    bestFor: "Luxury weddings, large guest counts, and Indian or other multi-event weddings. Covers 16 hours in one day, or two events such as a 4-hour sangeet plus a 12-hour wedding day.",
    receive: [
      "1,500+ edited photos, 40 with high-end retouching",
      "10-20 minute documentary-style film",
      "Separate ceremony, toasts and dances films",
      "60-second teaser plus 5 social reels",
      "1.5-hour engagement session and rehearsal dinner coverage",
      "10x10 wedding album included",
      "All raw video clips",
      "10 sneak-peek photos within 24 hours",
    ],
    bring: [
      "Two photographers and two cinematographers",
      "Full lighting kit and drone, if FAA rules, venue and weather allow",
      "Microphones on the couple and officiant, plus backup recorders",
      "Two places covered at once, such as both families getting ready",
      "Written timeline, shot list and a venue visit",
      "Album design and proofing",
      "Editing, color work, cloud backup and a second backup drive",
    ],
    notIncluded: ["Livestream (+$1,250)", "Dedicated content creator (+$950)"],
    delivery: { sneakPeek: "10 photos in 24 hours", gallery: "6 weeks", film: "12 weeks" },
  },

  // ----- Indian and other multi-event weddings (Part 2) -----
  {
    id: "two_day_wedding",
    categories: ["multi_event_wedding"],
    name: "Event day + wedding day",
    price: 9400,
    days: 2,
    hoursLabel: "Essential-level event day + Premier wedding day",
    team: "Event day: 2 people · Wedding day: 3 people + drone + lights",
    builtFrom: ["essential", "premier"],
    extraHourRate: 350,
    bestFor: "One event day plus the wedding day, such as sangeet and wedding.",
    receive: [
      "Event day: everything in Essential (4 hours, 300+ photos, 3-5 min highlight film)",
      "Wedding day: everything in Premier (14 hours, 1,000+ photos, 8-15 min cinematic film)",
    ],
    bring: ["The Essential team for the event day", "The Premier team for the wedding day"],
    notIncluded: ["Raw video clips (+$550)"],
    delivery: { sneakPeek: "10 photos in 24 hours (wedding day)", gallery: "6 weeks", film: "10 weeks" },
  },
  {
    id: "three_day_wedding",
    categories: ["multi_event_wedding"],
    name: "Three-day wedding",
    price: 11900,
    days: 3,
    hoursLabel: "Two Essential-level event days + Premier wedding day",
    team: "Event days: 2 people · Wedding day: 3 people + drone + lights",
    builtFrom: ["essential", "essential", "premier"],
    extraHourRate: 350,
    bestFor: "Three days, such as mehndi, sangeet and wedding.",
    receive: [
      "Two event days: everything in Essential for each day",
      "Wedding day: everything in Premier (14 hours, 1,000+ photos, 8-15 min cinematic film)",
    ],
    bring: ["The Essential team for each event day", "The Premier team for the wedding day"],
    notIncluded: ["Raw video clips (+$550)"],
    delivery: { sneakPeek: "10 photos in 24 hours (wedding day)", gallery: "6 weeks", film: "10 weeks" },
  },

  // ----- Small events (Part 3) -----
  {
    id: "quick_session",
    categories: ["small_event"],
    name: "Quick Session",
    price: 300,
    hours: 1,
    team: "1 photographer",
    people: 1,
    photos: "60+",
    video: "None",
    drone: false,
    extraHourRate: 175,
    hasVideo: false,
    bestFor: "Graduation, family, maternity.",
    receive: ["60+ edited photos", "3 quick-preview photos in 48 hours", "Online gallery with print release"],
    notIncluded: ["Video", "Drone"],
    delivery: { previews: "3 photos in 48 hours", gallery: "2 weeks" },
  },
  {
    id: "mini_moment",
    categories: ["small_event"],
    name: "Mini Moment",
    price: 450,
    hours: 2,
    team: "1 photographer",
    people: 1,
    photos: "100+",
    video: "None",
    drone: false,
    extraHourRate: 175,
    hasVideo: false,
    bestFor: "Engagement, birthday, shower, small gathering.",
    receive: ["100+ edited photos", "5 quick-preview photos in 48 hours", "Online gallery with print release"],
    notIncluded: ["Video", "Drone"],
    delivery: { previews: "5 photos in 48 hours", gallery: "2 weeks" },
  },
  {
    id: "photo_reel",
    categories: ["small_event"],
    name: "Photo + Reel",
    price: 700,
    hours: 2,
    team: "1 photographer who also shoots vertical video",
    people: 1,
    photos: "120+",
    video: "60-90 sec vertical reel",
    drone: false,
    extraHourRate: 200,
    hasVideo: true,
    bestFor: "Proposal, birthday or anniversary to share online.",
    receive: ["120+ edited photos", "60-90 second vertical reel", "10 quick-preview photos in 48 hours", "Online gallery with print release"],
    notIncluded: ["Highlight film", "Drone"],
    delivery: { previews: "10 photos in 48 hours", gallery: "2 weeks", reel: "2 weeks" },
  },
  {
    id: "event_film",
    categories: ["small_event"],
    name: "Event + Film",
    price: 1300,
    hours: 2,
    team: "Photographer + videographer",
    people: 2,
    photos: "150+",
    video: "1-2 min highlight film",
    drone: false,
    extraHourRate: 300,
    hasVideo: true,
    bestFor: "Milestone party, corporate mixer.",
    receive: ["150+ edited photos", "1-2 minute highlight film", "Cleaned-up speech audio", "10 quick-preview photos in 48 hours", "Online gallery with print release"],
    notIncluded: ["Drone", "Album"],
    delivery: { previews: "10 photos in 48 hours", gallery: "3 weeks", film: "4 weeks" },
  },
  {
    id: "full_event",
    categories: ["small_event"],
    name: "Full Event",
    price: 1800,
    hours: 4,
    team: "Photographer + videographer",
    people: 2,
    photos: "250+",
    video: "2-3 min highlight film + 60-sec reel",
    drone: "Yes, for outdoor events",
    extraHourRate: 300,
    hasVideo: true,
    bestFor: "Gala, corporate or brand event, large party.",
    receive: ["250+ edited photos", "2-3 minute highlight film", "60-second reel", "Cleaned-up speech audio", "Drone for outdoor events", "10 quick-preview photos in 48 hours", "Online gallery with print release"],
    notIncluded: ["Album", "Third shooter"],
    delivery: { previews: "10 photos in 48 hours", gallery: "3 weeks", film: "5 weeks" },
  },
];

// ---------------------------------------------------------------------------
// Add-ons
//   price            fixed price
//   priceByPackage   price depends on the chosen package
//   percent          percentage of the subtotal (rush)
//   appliesTo        package ids that can add it
//   includedIn       package ids that already include it (shown as "Included")
//   requires         other add-on ids that must also be selected
//   requiresOutdoor  only for outdoor events
// ---------------------------------------------------------------------------
const WEDDING_PACKAGES = ["essential", "classic", "signature", "premier", "legacy", "two_day_wedding", "three_day_wedding"];
const SMALL_PACKAGES = ["quick_session", "mini_moment", "photo_reel", "event_film", "full_event"];

export const ADDONS = [
  // ----- Wedding add-ons (Part 2) -----
  {
    id: "engagement_session",
    group: "wedding",
    label: "Engagement session, 1 hour",
    description: "A relaxed 1-hour session before the wedding.",
    price: 450,
    appliesTo: ["essential"],
    includedIn: ["classic", "signature", "premier", "legacy", "two_day_wedding", "three_day_wedding"],
  },
  {
    id: "drone_wedding",
    group: "wedding",
    label: "Drone",
    description: "Aerial photos and a short edited clip.",
    price: 250,
    appliesTo: ["essential"],
    includedIn: ["classic", "signature", "premier", "legacy", "two_day_wedding", "three_day_wedding"],
    note: "Drone flights depend on FAA rules, the venue and the weather.",
  },
  {
    id: "toasts_film",
    group: "wedding",
    label: "Full toasts film",
    description: "Every toast, edited into its own film.",
    price: 400,
    appliesTo: ["essential", "classic"],
    includedIn: ["signature", "premier", "legacy", "two_day_wedding", "three_day_wedding"],
  },
  {
    id: "raw_video_wedding",
    group: "wedding",
    label: "All raw video clips",
    description: "Every unedited clip from the day.",
    price: 550,
    appliesTo: ["essential", "classic", "signature", "premier", "two_day_wedding", "three_day_wedding"],
    includedIn: ["legacy"],
  },
  {
    id: "rehearsal_dinner",
    group: "wedding",
    label: "Rehearsal dinner coverage, 2 hours",
    description: "Minimum 2 hours.",
    price: 600,
    appliesTo: ["essential", "classic", "signature", "premier", "two_day_wedding", "three_day_wedding"],
    includedIn: ["legacy"],
  },
  {
    id: "album_10x10",
    group: "wedding",
    label: "Wedding album, 10x10",
    description: "A printed 10x10 album. Starting price; final price depends on the album you choose.",
    price: 600,
    priceIsFrom: true,
    // Premier (and the bundles built on Premier) include a $500 album credit.
    creditByPackage: { premier: 500, two_day_wedding: 500, three_day_wedding: 500 },
    appliesTo: ["essential", "classic", "signature", "premier", "two_day_wedding", "three_day_wedding"],
    includedIn: ["legacy"],
  },
  {
    id: "content_creator",
    group: "wedding",
    label: "Wedding content creator, 8 hours",
    description: "Behind-the-scenes photos and short videos for social media.",
    price: 950,
    appliesTo: WEDDING_PACKAGES,
  },
  {
    id: "livestream_wedding",
    group: "wedding",
    label: "Live stream, 2 cameras",
    description: "Up to 5 hours, recorded.",
    price: 1250,
    appliesTo: WEDDING_PACKAGES,
    note: "You or the venue provide reliable internet. A stream cannot be redone if it fails.",
  },

  // ----- Small-event extras (Part 3) -----
  {
    id: "drone_small",
    group: "small_event",
    label: "Drone",
    description: "Aerial photos and a 30-60 second edited clip. Outdoor only.",
    price: 250,
    appliesTo: ["quick_session", "mini_moment", "photo_reel", "event_film"],
    includedIn: ["full_event"],
    requiresOutdoor: true,
    note: "Outdoor events only. Drone flights depend on FAA rules, the venue and the weather.",
  },
  {
    id: "livestream_1cam",
    group: "small_event",
    label: "Live stream, 1 camera",
    description: "Up to 3 hours, a private link to watch, and a recording.",
    price: 750,
    appliesTo: SMALL_PACKAGES,
    excludes: ["livestream_2cam"],
    note: "You or the venue provide reliable internet.",
  },
  {
    id: "livestream_2cam",
    group: "small_event",
    label: "Live stream, 2 cameras",
    description: "Up to 5 hours, switching between cameras, and a recording.",
    price: 1250,
    appliesTo: SMALL_PACKAGES,
    excludes: ["livestream_1cam"],
    note: "You or the venue provide reliable internet.",
  },
  {
    id: "short_reel",
    group: "small_event",
    label: "Short reel",
    description: "60-90 second vertical reel for Instagram.",
    price: 250,
    appliesTo: ["quick_session", "mini_moment"],
    includedIn: ["photo_reel", "full_event"],
  },
  {
    id: "highlight_video",
    group: "small_event",
    label: "Highlight video",
    description: "1-2 minute edited film. Adds a videographer.",
    price: 850,
    appliesTo: ["mini_moment"],
    includedIn: ["event_film", "full_event"],
  },
  {
    id: "full_event_video",
    group: "small_event",
    label: "Full event video",
    description: "One continuous, lightly cleaned recording of the whole event, with no highlight cuts.",
    priceByPackage: { mini_moment: 300, event_film: 300, full_event: 500 },
    priceLabel: "+$300 (2 hr) or +$500 (4 hr)",
    appliesTo: ["mini_moment", "event_film", "full_event"],
    requiresByPackage: { mini_moment: ["highlight_video"] },
    note: "Needs a videographer.",
  },
  {
    id: "raw_video_small",
    group: "small_event",
    label: "RAW video clips",
    description: "Unedited clips straight from the camera.",
    priceByPackage: { mini_moment: 250, photo_reel: 250, event_film: 250, full_event: 400 },
    priceLabel: "+$250 (2 hr) or +$400 (4 hr)",
    appliesTo: ["mini_moment", "photo_reel", "event_film", "full_event"],
    requiresByPackage: { mini_moment: ["highlight_video"] },
    note: "Only on packages with video.",
  },
  {
    id: "unedited_photos",
    group: "small_event",
    label: "Unedited photos",
    description: "Every photo straight from the camera, no editing.",
    price: 150,
    appliesTo: SMALL_PACKAGES,
  },
  {
    id: "rush_delivery",
    group: "small_event",
    label: "Rush delivery",
    description: "Everything in half the usual time.",
    percent: 25,
    appliesTo: SMALL_PACKAGES,
    note: "25% of your package, extra hours and editing extras (live streams are not included in the 25%).",
  },
];

export const MAX_EXTRA_HOURS = 8;

// Small-event types and the packages that fit them ("Which package fits which event").
export const EVENT_TYPES = {
  wedding: [
    { id: "wedding", label: "Wedding" },
    { id: "elopement", label: "Courthouse / micro wedding" },
  ],
  multi_event_wedding: [
    { id: "indian_wedding", label: "Indian wedding" },
    { id: "multi_event_wedding", label: "Other multi-event wedding" },
  ],
  small_event: [
    { id: "graduation", label: "Graduation", suggested: ["quick_session"] },
    { id: "family", label: "Family", suggested: ["quick_session", "mini_moment"] },
    { id: "maternity", label: "Maternity", suggested: ["mini_moment"] },
    { id: "engagement", label: "Engagement", suggested: ["mini_moment"] },
    { id: "proposal", label: "Proposal", suggested: ["mini_moment", "photo_reel"] },
    { id: "birthday", label: "Birthday", suggested: ["mini_moment", "photo_reel", "event_film"] },
    { id: "anniversary", label: "Anniversary", suggested: ["mini_moment", "photo_reel"] },
    { id: "shower", label: "Shower", suggested: ["mini_moment"] },
    { id: "corporate", label: "Corporate", suggested: ["event_film", "full_event"] },
    { id: "gala", label: "Gala", suggested: ["full_event"] },
    { id: "brand_event", label: "Brand event", suggested: ["full_event"], note: "Usage rights for brand work are quoted separately." },
    { id: "other", label: "Something else" },
  ],
};

export const CATALOG = {
  version: CATALOG_VERSION,
  currency: CURRENCY,
  business: BUSINESS,
  categories: CATEGORIES,
  packages: PACKAGES,
  addons: ADDONS,
  eventTypes: EVENT_TYPES,
  maxExtraHours: MAX_EXTRA_HOURS,
};

export default CATALOG;
